[package]
name = "l2"
version = "0.1.0"
authors = ["Adrian Mucha <kestarumper8@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
csv = "1.1"
