[package]
name = "l1"
version = "0.1.0"
authors = ["Adrian Mucha <kestarumper8@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotlib = "0.4.0"
rand = "0.7.3"
clap = "2.33.0"